### PR TITLE
Implement an atomic lock check action.

### PR DESCRIPTION
**Pull request by josecv**
Analogous to a hardware lock check, this will atomically try to acquire
a specified lock (and wait until it can), then immediately release the lock.

Co-authored-by: Rafay <rafay@autonomic.ai>

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@josecv Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=concourse/pool-resource&pullRequestId=37)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=concourse/pool-resource&pullRequestId=37) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by vito** [comment]
I'm interested in hearing the use case for this before merging, in the interest of minimizing knobs. What does this solve over having two `put`s? What part of your workflow requires just waiting on a lock without holding it before continuing? (Is that really safe?)

**Comment by vito** [comment]
Interesting. This will indeed help, but it still won't completely save you from aborts. Someone could click 'abort' and cause the `put` operation itself to be interrupted in between the claim and unclaim.

Going back to your use case, it actually sounds a bit like a read-write lock or exclusive/shared acquire semantics. This is discussed in some form as https://github.com/concourse/pool-resource/issues/35 and https://github.com/concourse/concourse/issues/842. Some form of that feels like a better approach to me - the utility of the `check` verb here was not immediately apparent. I may be missing something here but it also seems like there's nothing preventing the 'freezer' or 'cleanup' job (i.e. the exclusive acquirer) from running while existing deploys are in flight, because they just immediately release their lock.

I'd be happy to work with y'all towards a proposed API/approach if you're interested.

**Comment by vito** [comment]
Sorry but I'm gonna close this out; I'm still fishy on this approach to the problem. Happy to hash out the other stuff I mentioned at some point though.

**Comment by alnavart** [comment]
Hi! I'm experiencing the same issue than @josecv commented on https://github.com/concourse/pool-resource/pull/37#issuecomment-391384885 
Are there any update on this approach about atomic operation? or maybe disallowing to abort on some specific steps..

**Pull request closed without merging**
