### PR TITLE
WIP - Actually vendor dependencies

### PR DESCRIPTION
**Pull request by zachgersh**
I am going to be using this as my base for adding the ability to claim a lock with metadata. Look out for that next.

### CODE REVIEW

**Comment by chendrix** [comment]
You forgot to change the build scripts @zachgersh !

**Comment by zachgersh** [comment]
I will add that :)

**Comment by chendrix** [comment]
The `ci/build` script is also broken. We cannot do a `go install github.com/onsi/ginkgo/ginkgo` anymore.

**Comment by zachgersh** [comment]
@chendrix - what other scripts were broken? I couldn't see anything that seemed troublesome beyond that.

**Comment by chendrix** [comment]
@zachgersh looks like you got it all.

**Comment by chendrix** [comment]
This fails building

```
$ fly -t ci execute -c build.yml -i pool-resource=. -x
executing build 36997
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  830k    0  830k    0     0  1870k      0 --:--:-- --:--:-- --:--:-- 2626k
initializing
Pulling concourse/pool-resource-test@sha256:1637958f4c79f4f3e3532368923669299001c92e2b82edbd3b55967ea20b4680...
sha256:1637958f4c79f4f3e3532368923669299001c92e2b82edbd3b55967ea20b4680: Pulling from concourse/pool-resource-test
7bdbf7d44e96: Pulling fs layer
a3ed95caeb02: Pulling fs layer
572491670514: Pulling fs layer
af0ff53965c3: Pulling fs layer
dd53cb3268f0: Pulling fs layer
df8fde8bb9c5: Pulling fs layer
624dd595e975: Pulling fs layer
bf048c661b7e: Pulling fs layer
5e5602b8ec15: Pulling fs layer
67cd76a0ee81: Pulling fs layer
ee0e2d87ffa8: Pulling fs layer
b0c40fec6c22: Pulling fs layer
a0f5fe3cbf26: Pulling fs layer
4d22f09a78ae: Pulling fs layer
e2b254e2da83: Pulling fs layer
af0ff53965c3: Waiting
dd53cb3268f0: Waiting
df8fde8bb9c5: Waiting
5e5602b8ec15: Waiting
624dd595e975: Waiting
a0f5fe3cbf26: Waiting
bf048c661b7e: Waiting
67cd76a0ee81: Waiting
ee0e2d87ffa8: Waiting
b0c40fec6c22: Waiting
4d22f09a78ae: Waiting
a3ed95caeb02: Download complete
7bdbf7d44e96: Verifying Checksum
7bdbf7d44e96: Download complete
572491670514: Verifying Checksum
572491670514: Download complete
7bdbf7d44e96: Pull complete
a3ed95caeb02: Pull complete
572491670514: Pull complete
df8fde8bb9c5: Download complete
dd53cb3268f0: Verifying Checksum
dd53cb3268f0: Download complete
bf048c661b7e: Verifying Checksum
bf048c661b7e: Download complete
5e5602b8ec15: Download complete
af0ff53965c3: Verifying Checksum
af0ff53965c3: Download complete
67cd76a0ee81: Verifying Checksum
67cd76a0ee81: Download complete
ee0e2d87ffa8: Download complete
b0c40fec6c22: Verifying Checksum
4d22f09a78ae: Verifying Checksum
4d22f09a78ae: Download complete
a0f5fe3cbf26: Verifying Checksum
a0f5fe3cbf26: Download complete
af0ff53965c3: Pull complete
e2b254e2da83: Verifying Checksum
e2b254e2da83: Download complete
dd53cb3268f0: Pull complete
df8fde8bb9c5: Pull complete
624dd595e975: Verifying Checksum
624dd595e975: Download complete
624dd595e975: Pull complete
bf048c661b7e: Pull complete
5e5602b8ec15: Pull complete
67cd76a0ee81: Pull complete
ee0e2d87ffa8: Pull complete
b0c40fec6c22: Pull complete
a0f5fe3cbf26: Pull complete
4d22f09a78ae: Pull complete
e2b254e2da83: Pull complete
Digest: sha256:1637958f4c79f4f3e3532368923669299001c92e2b82edbd3b55967ea20b4680
Status: Downloaded newer image for concourse/pool-resource-test@sha256:1637958f4c79f4f3e3532368923669299001c92e2b82edbd3b55967ea20b4680

Successfully pulled concourse/pool-resource-test@sha256:1637958f4c79f4f3e3532368923669299001c92e2b82edbd3b55967ea20b4680.

running gopath/src/github.com/concourse/pool-resource/ci/build
+ export TMPDIR=/tmp
+ TMPDIR=/tmp
+ export GOPATH=/tmp/build/e55deab7/gopath
+ GOPATH=/tmp/build/e55deab7/gopath
+ export GOBIN=/tmp/build/e55deab7/gopath/bin
+ GOBIN=/tmp/build/e55deab7/gopath/bin
+ export PATH=/tmp/build/e55deab7/gopath/bin:/go/bin:/usr/src/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ PATH=/tmp/build/e55deab7/gopath/bin:/go/bin:/usr/src/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+ BUILD_DIR=/tmp/build/e55deab7/built-resource
+ go install github.com/concourse/pool-resource/vendor/github.com/onsi/ginkgo/ginkgo
gopath/src/github.com/concourse/pool-resource/vendor/github.com/onsi/ginkgo/ginkgo/main.go:127:2: cannot find package "github.com/onsi/ginkgo/config" in any of:
	/usr/src/go/src/github.com/onsi/ginkgo/config (from $GOROOT)
	/tmp/build/e55deab7/gopath/src/github.com/onsi/ginkgo/config (from $GOPATH)
gopath/src/github.com/concourse/pool-resource/vendor/github.com/onsi/ginkgo/ginkgo/convert_command.go:6:2: cannot find package "github.com/onsi/ginkgo/ginkgo/convert" in any of:
	/usr/src/go/src/github.com/onsi/ginkgo/ginkgo/convert (from $GOROOT)
	/tmp/build/e55deab7/gopath/src/github.com/onsi/ginkgo/ginkgo/convert (from $GOPATH)
gopath/src/github.com/concourse/pool-resource/vendor/github.com/onsi/ginkgo/ginkgo/build_command.go:9:2: cannot find package "github.com/onsi/ginkgo/ginkgo/interrupthandler" in any of:
	/usr/src/go/src/github.com/onsi/ginkgo/ginkgo/interrupthandler (from $GOROOT)
	/tmp/build/e55deab7/gopath/src/github.com/onsi/ginkgo/ginkgo/interrupthandler (from $GOPATH)
gopath/src/github.com/concourse/pool-resource/vendor/github.com/onsi/ginkgo/ginkgo/bootstrap_command.go:15:2: cannot find package "github.com/onsi/ginkgo/ginkgo/nodot" in any of:
	/usr/src/go/src/github.com/onsi/ginkgo/ginkgo/nodot (from $GOROOT)
	/tmp/build/e55deab7/gopath/src/github.com/onsi/ginkgo/ginkgo/nodot (from $GOPATH)
gopath/src/github.com/concourse/pool-resource/vendor/github.com/onsi/ginkgo/ginkgo/build_command.go:10:2: cannot find package "github.com/onsi/ginkgo/ginkgo/testrunner" in any of:
	/usr/src/go/src/github.com/onsi/ginkgo/ginkgo/testrunner (from $GOROOT)
	/tmp/build/e55deab7/gopath/src/github.com/onsi/ginkgo/ginkgo/testrunner (from $GOPATH)
gopath/src/github.com/concourse/pool-resource/vendor/github.com/onsi/ginkgo/ginkgo/main.go:128:2: cannot find package "github.com/onsi/ginkgo/ginkgo/testsuite" in any of:
	/usr/src/go/src/github.com/onsi/ginkgo/ginkgo/testsuite (from $GOROOT)
	/tmp/build/e55deab7/gopath/src/github.com/onsi/ginkgo/ginkgo/testsuite (from $GOPATH)
gopath/src/github.com/concourse/pool-resource/vendor/github.com/onsi/ginkgo/ginkgo/watch_command.go:12:2: cannot find package "github.com/onsi/ginkgo/ginkgo/watch" in any of:
	/usr/src/go/src/github.com/onsi/ginkgo/ginkgo/watch (from $GOROOT)
	/tmp/build/e55deab7/gopath/src/github.com/onsi/ginkgo/ginkgo/watch (from $GOPATH)
gopath/src/github.com/concourse/pool-resource/vendor/github.com/onsi/ginkgo/ginkgo/suite_runner.go:12:2: cannot find package "github.com/onsi/ginkgo/reporters/stenographer/support/go-colorable" in any of:
	/usr/src/go/src/github.com/onsi/ginkgo/reporters/stenographer/support/go-colorable (from $GOROOT)
	/tmp/build/e55deab7/gopath/src/github.com/onsi/ginkgo/reporters/stenographer/support/go-colorable (from $GOPATH)
gopath/src/github.com/concourse/pool-resource/vendor/github.com/onsi/ginkgo/ginkgo/run_command.go:13:2: cannot find package "github.com/onsi/ginkgo/types" in any of:
	/usr/src/go/src/github.com/onsi/ginkgo/types (from $GOROOT)
	/tmp/build/e55deab7/gopath/src/github.com/onsi/ginkgo/types (from $GOPATH)
failed
```

**Comment by zachgersh** [comment]
Don't actually review this until I take the WIP tag off of the header.

**Comment by chendrix** [comment]
any update to this @zachgersh

**Comment by zachgersh** [comment]
Yeah - look at how many commits are on my branch - it's coming 😂

**Comment by vito** [comment]
I'm going to close this for now; once something's ready for a review + merge, feel free to re-submit.

**Pull request closed without merging**
